
[site]
url = "http://localhost"
name = "Demo"
description = "Demonstration of Zine."
edit_url = "https://github.com/zineland/zine/edit/master/demo"
menu = [
    { name = "About", url = "/about" },
    { name = "Github", url = "https://github.com" },
]

[authors]
zine-team = { name = "Zine Team", bio = "The Zine Team.", editor = true }
admin = { name = "Admin" }

[topics]
async = {}
game = { name = "Game development", description = "Topic of rust game development." }
