
[site]
url = "http://localhost"
name = "Demo"
description = "Demonstration of Zine."
menu = [
    { name = "About", url = "/about" },
    { name = "Github", url = "https://github.com" },
]

[authors]
zine-team = { name = "Zine Team", bio = "The Zine Team." }

[[season]]
slug = "cloud"
number = 1
title = "Season #1"
summary = "Summary of Season #1"
path = "season-1"

[[season]]
slug = "dev"
number = 2
title = "Season #2"
summary = "Summary of Season #2"
path = "season-2"
