
[site]
url = "http://localhost"
name = "Demo"
description = "Demonstration of Zine."
menu = [
    { name = "About", url = "/about" },
    { name = "Github", url = "https://github.com" },
]

[authors]
zine-team = { name = "Zine Team", bio = "The Zine Team.", editor = true }
admin = { name = "Admin" }

[[issue]]
slug = "cloud"
number = 1
title = "Issue 1"
path = "issue-1"

[[issue]]
slug = "dev"
number = 2
title = "Issue 2"
path = "issue-2"
