
[[article]]
slug = "first"
file = "first.md"
title = "First article"
author = "zine-team"
cover = "/static/duck.png"
pub_date = "2022-03-25"
publish = true
featured = true

[[article]]
slug = "second"
file = "second.md"
title = "Second article"
author = "zine-team"
cover = "/static/duck.png"
pub_date = "2022-04-25"
publish = false
featured = true
