name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Build
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo build
    - name: Run test
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo test
    - name: Publish test
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo publish --dry-run